name: Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"
    - name: Lint Check
      run: |
        ruff .
    - name: Test
      run: |
        pytest
